Repository TailorDev/Watson, pull requests merged in 2019-08, with the labels that each got.

#298 Did a typo fix
  docs/index.md
Labels: improvement

#300 Fix fatal AttributeError using Arrow 0.14.5
  CHANGELOG.md
  scripts/fuzzer.py
  watson/cli.py
  watson/utils.py
Labels: improvement, needs review

#303 Bump release to 1.8.0
  CHANGELOG.md
  docs/about/release-notes.md
  watson/version.py
Labels: TailorDev
