Repository TailorDev/Watson, pull requests merged in 2019-10, with the labels that each got.

#322 Fix #321
  CHANGELOG.md
  watson/cli.py
  watson/watson.py
Labels: improvement

#318 Enable git-like did-you-mean feature
  CHANGELOG.md
  requirements.txt
  watson/cli.py
Labels: feature

#330 Use Arrows for_json for JSON output
  CHANGELOG.md
  tests/test_utils.py
  watson/cli.py
  watson/utils.py
Labels: bug, hacktoberfest, needs review

#331 Fix aggregate command with option --json
  watson/cli.py
Labels: bug

#332 Update cli.py
  watson/cli.py
Labels: easy pick, hacktoberfest, improvement
