Repository TailorDev/Watson, pull requests merged in 2019-03, with the labels that each got.

#262 Prepare release 1.7.0
  CHANGELOG.md
  docs/about/release-notes.md
  watson/version.py
Labels: TailorDev

#263 Fix missing link for the latest release
  docs/about/release-notes.md
Labels: bug, easy pick

#264 Update ZSH completion file
  CHANGELOG.md
  watson.zsh-completion
Labels: improvement, needs review

#251 Make sure bad dates in add command give nice cli errors instead of tr…
  watson/cli.py
Labels: improvement
