Repository TailorDev/Watson, pull requests merged in 2020-06, with the labels that each got.

#369 Add option to control the order of the days in the `log` output
  CHANGELOG.md
  docs/user-guide/configuration.md
  tests/test_utils.py
  watson/cli.py
Labels: improvement

#364 Allow specification of start time via `start_at`
  CHANGELOG.md
  tests/test_cli.py
  tests/test_watson.py
  watson/cli.py
  watson/watson.py
Labels: feature

#382 Add after edit check that start is in the past, closes #381
  CHANGELOG.md
  watson/cli.py
Labels: improvement

#350 Allow to force enable/disable colored output
  CHANGELOG.md
  watson/cli.py
Labels: improvement, needs review
