Repository TailorDev/Watson, pull requests merged in 2020-05, with the labels that each got.

#372 Limit arrow version to under 0.15.6
  requirements.txt
Labels: bug, easy pick

#366 Avoid dubble newlines in csv output
  CHANGELOG.md
  tests/test_utils.py
  watson/utils.py
Labels: improvement, question

#376 [Requirements] add colorama for Windows
  requirements.txt
  watson/cli.py
Labels: improvement

#339 Require Click>=7.0 (fix #338)
  requirements.txt
Labels: bug

#378 Bump release to 1.9.0
  CHANGELOG.md
  docs/about/release-notes.md
  watson/version.py
Labels: TailorDev
