Repository TailorDev/Watson, pull requests merged in 2021-03, with the labels that each got.

#411 issue #391: Watson now supports setting the TZ env variable.
  CHANGELOG.md
  tests/test_cli.py
  watson/cli.py
Labels: feature

#415 Bump release to 2.0.0
  CHANGELOG.md
  docs/about/release-notes.md
  watson/version.py
Labels: TailorDev

#418 Gracefully handle empty stop time
  CHANGELOG.md
  tests/test_watson.py
  watson/frames.py
Labels: bug, critical
