Repository TailorDev/Watson, pull requests merged in 2022-05, with the labels that each got.

#471 Fix click 8 compatibility issues
  requirements.txt
  watson/cli.py
Labels: bug, critical

#472 Bump release to 2.1.0
  CHANGELOG.md
  docs/about/release-notes.md
  watson.zsh-completion
  watson/version.py
Labels: TailorDev

#449 Use the mock standard module
  requirements-dev.txt
  tests/__init__.py
  tests/test_utils.py
Labels: improvement
